[package]
name = "nostd_io"
version = "0.1.0"
authors = ["Eric-Keeling <Eric.Keeling@gmail.com>"]
edition = "2018"

[dependencies]
volatile = "0.2.6"
spin = "0.7.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]